### ISSUE TITLE
About generating GT code

### ISSUE THREAD

**Issue by iiiifan** [adosum/3D-FlowNet#1]
Nice work!
I used your code to generate gt, but I get following error:
![2022-02-20 23-05-42 的屏幕截图](https://user-images.githubusercontent.com/58362754/154849400-c2ae877e-1181-4997-8b9d-b8738d00ffb7.png)
How to fix this? Thank you~

**Comment by adosum** [comment]
This is because of a simple indexing problem, I have already fixed it.
